pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git url: 'https://github.com/bahriddin-af/JenkinsCI.git', credentialsId: 'github-pat'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t jenkinsci-api .'
            }
        }
        stage('Run Docker Container') {
            steps {
                sh 'docker run -d -p 5000:80 jenkinsci-api'
            }
        }
    }
}
