pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                dir('src/JenkinsCI.API') {
                    bat 'docker build -t jenkinsci-api .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                bat 'docker run -d -p 5000:80 jenkinsci-api'
            }
        }
    }
}
